---
- name: install redis
  apt: name=redis state=latest
  when: ansible_os_family == "Debian"

- name: install redis
  yum: name=redis state=latest
  when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"

- name: start redis
  service: name=redis state=restarted enabled=yes
  when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"

  #- name: enable redis
  #service: name=redis state=enabled
  #when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"

