---
- name: install mongodb
  apt: name=mongodb state=latest
  when: ansible_os_family == "Debian"

- name: install mongodb
  yum: pkg={{ item }} state=present
  with_items:
    - mongodb
    - mongodb-server
  when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"

- name: start mongo
  service: name=mongod state=started enabled=yes
  when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"

  #- name: start mongo
  #service: name=mongod state=enabled
  #when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"

