---
- name: Install java 
  apt: name=openjdk-8-jdk state=present
  when: ansible_os_family == "Debian"

- name: Install Java
  yum: name=java state=present
  when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"
