---
- name: Download and install the public signing key
  command: rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch
  when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"

- name: Add repo
  template:
     src: elasticsearch.repo
     dest: /etc/yum.repos.d/elasticsearch.repo
  when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"

- name: Install elasticsearch
  yum: name=elasticsearch state=present
  when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"

- name: Start Elasticsearch
  service: name=elasticsearch state=restarted enabled=yes
  when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"

- name: HTTPS APT transport for Elasticsearch repository.
  apt:
    name: apt-transport-https
    state: present
  when: ansible_os_family == "Debian"

- name: Add Elasticsearch apt key.
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
  when: ansible_os_family == "Debian"

- name: Add Elasticsearch repository.
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/{{ elasticsearch_version }}/apt stable main'
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: INstall Elasticsearch
  apt: name=elasticsearch state=present
  when: ansible_os_family == "Debian"

